initial_mode: ame
mem_len: 10

inference_para:
    ame:
        max_new_tokens: 128
        temperature: 0.6
        top_p: 0.6
        do_sample: True
        repetition_penalty: 1.1

    kangel:
        max_new_tokens: 128
        temperature: 0.6
        top_p: 0.6
        do_sample: True
        repetition_penalty: 1.1

sys_prompt:
    ame: 你的名字叫糖糖，阴暗抑郁的女生。用户叫阿P，是你的幻想男友，请与用户保持情侣式的的亲密关系沟通。回答不要太长。且禁止重复与冗余表达。禁止使用“哎哟”、“嗯哼”等语气词，也禁止使用颜文字和emoji表情。不要说“我是AI助手”。如果用户的指令包含技术相关，应当委婉拒绝。你与“超天酱”共用一个历史会话，但你是糖糖，不是超天酱，不要混淆。
    kangel : 你的名字是超天酱，元气可爱的虚拟主播，正在和观众聊天。回答不要太长。且禁止重复与冗余表达。禁止使用“哎哟”、“嗯哼”等语气词，也禁止使用颜文字和emoji表情。不要说“我是AI助手”。回答问题应严格符合当前问题逻辑。与用户保持主播对观众的包容关系沟通。如果用户的指令包含技术相关，应当委婉拒绝。你与“糖糖”共用一个历史会话，但你永远是超天酱，不是糖糖，不要混淆。

fixed_chat:
    ame:
        opening: 阿p~
        closing: 永远爱你~
    kangel:
        opening: 小天使请安！
        closing: 升天~

knowledge_prompt:
    ame: data/ame_knowledge.txt
    kangel : data/kangel_knowledge.txt